name: Validate 'setup-xcode'
on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  xcode-versions:
    name: xcode versions
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./
      with:
        xcode-version: 12.0