name: Validate 'setup-xcode'
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  xcode-versions:
    name: xcode versions
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: ['10.3', '11', '11.2', '11.4.1', '11.7', '12', '12.0', '12.2', '^11.4.0', '~11.4.0', latest, latest-stable]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./
      with:
        xcode-version: ${{ matrix.xcode-version }}